export {default as MainHeader} from './MainHeader'
export {default as MainNavbar} from './MainNavbar'
export {default as MainFooter} from './MainFooter'
export {default as Subscribe} from './Subscribe'
export {default as DiscountBar} from './DiscountBar'